name: collinkleest.com

networks:
  kong:
    driver: bridge
    name: kong-net

services:
  webapp:
    container_name: collinkleest-website
    build: .
    networks:
      - kong
    ports:
      - 3000:80 # Map host port 3000 to container port 80 (Nginx)
    restart: always
    labels:
      - 'collinkleest.com'
      - 'nextjs'
