# .github/workflows/ci.yaml

name: collinkleest.com portfolio workflow

on:
  push:
    branches: ['*'] # Runs on any branch
  pull_request: # Also runs on PRs
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js 23.6.0
        uses: actions/setup-node@v4
        with:
          node-version: 23.6.0

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 10.6.2

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Code Formatting
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./out
