# .github/workflows/ci.yaml

name: collinkleest.com portfolio workflow

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # ci job
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install PNPM
        run: corepack enable && corepack prepare pnpm@10.6.2 --activate

      - name: Use Node.js 23.6.0
        uses: actions/setup-node@v4
        with:
          node-version: 23.6.0
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Code Formatting
        run: pnpm format:check

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./out
