# .github/workflows/deploy-status.yaml

name: collinkleest.com deployment status

on:
  workflow_dispatch:

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - name: Start Application
        uses: collinkleest/remote-release@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command: |
            curl -X GET http://localhost:8001/upstreams/collinkleest-website-upstream/targets/ | grep :100
